### ISSUE TITLE
Question - How to use these lifestyles with the Classes.FromAssembly registration method?

### ISSUE THREAD

**Issue by slypete** [castleprojectcontrib/Castle.Windsor.Lifestyles#6]
Hi there, thanks for these lifestyles!

I can easily use them the Component.For registration method like so:

`container.Register(Component.For<IUserStore<ApplicationUser, int>>().ImplementedBy<UserStore>().LifeStyle.HybridPerWebRequestPerThread());`

But how do I use them with the Classes.FromAssembly registration method? 

`container.Register(Classes.FromAssembly(Assembly.GetAssembly(typeof(Manager<>))).BasedOn(typeof(Manager<>)).LifestylePerWebRequest());`

This returns BasedOnDescriptor instead of ComponentRegistration, so I'm not sure how to use these lifestyles with this registration.

Thanks for any insight,
Pete

**Comment by mausch** [comment]
Use `Configure` e.g.:

```
container.Register(Classes.FromAssembly(Assembly.GetAssembly(typeof(Manager<>)))
                            .BasedOn(typeof(Manager<>))
                            .Configure(x => x.LifeStyle.HybridPerWebRequestPerThread()));
```

**Comment by slypete** [comment]
Thanks a bunch @mausch!
